/*
 *  Copyright (C) 2017  S. van der Baan
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package net.vdbaan.issuefinder.model

class Finding {
    enum Severity {
        CRITICAL, HIGH, MEDIUM, LOW, INFO, UNKNOWN
    }

    static String CREATE = '''
CREATE TABLE finding (
id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
scanner     VARCHAR(64),
ip          VARCHAR(64),
hostName    VARCHAR(1000),
port        VARCHAR(64),
portStatus  VARCHAR(64),
protocol    VARCHAR(64),
service     VARCHAR(64),
plugin      LONGVARCHAR,
risk        VARCHAR(64),
summary     LONGVARCHAR,
baseCVSS    VARCHAR(64),
exploitable BOOLEAN
);
'''
    static String INSERT = 'INSERT INTO finding (scanner,ip,hostName,port,portStatus,protocol,service,plugin,risk,summary,baseCVSS,exploitable) ' +
            'values (?.scanner,?.ip,?.hostName,?.port,?.portStatus,?.protocol,?.service,?.plugin,?.risk,?.summary,?.baseCVSS,?.exploitable)'
    static String UPDATE = 'UPDATE finding SET scanner=?.scanner,ip=?.ip,hostName=?.hostName,port=?.port,portStatus=?.portStatus,protocol=?.protocol,service=?.service,plugin=?.plugin,risk=?.risk,summary=?.summary,baseCVSS=?.baseCVSS,exploitable=?.exploitable WHERE id=?.id'
//    static String UPDATE = 'UPDATE finding SET service=?.service WHERE id=?.id'
    static String SELECT = 'SELECT * FROM finding'
    static String COUNT = 'SELECT COUNT(*) FROM finding'
    static String DELETE_ALL = 'DELETE FROM finding'

    int id
    String scanner = ''
    String ip = ''
    String hostName = ''
    String port = ''
    String portStatus = ''
    String protocol = ''
    String service = ''
    String plugin = ''
    Severity severity = Severity.UNKNOWN
    String summary = ''
    String baseCVSS = '0.0'
    Boolean exploitable = false

    String getRisk() {
        return severity.toString()
    }

    @Override
    String toString() {
        return String.format("scanner:%s, source:%s:%s (%s), plugin:%s, severity:%s cvss:%s, exploitable:%b",
                scanner, ip, port, service, plugin, severity, baseCVSS, exploitable)
    }

    String fullDescription() {
        return String.format("scanner: %s\nsource: %s:%s\nservice: %s\nplugin: %s\nseverity: %s\n" +
                "=============================================\n" + "summary:\n%s\n",
                scanner, ip, port, service, plugin, severity, summary)
    }

    String htmlDescription() {
        return String.format("<h1 style='color:blue'>scanner: %s</h1><br/>source: %s:%s (%s/%s)<br/>hostname: %s<br/>service: %s<br/>plugin: %s<br/>severity: %s<br/>" +
                "<hr/>" + "summary:<br/>%s",
                scanner, ip, port, protocol, portStatus, hostName, service, plugin, severity, summary.replace('\n', '<br/>'))
    }
}
